#! /bin/sh
awk -F, '{
print $4 ", " $0
}' $* |
sort |
awk -F, '
# we don't have to assign to a variable before using it, because awk variables are initialized to the empty string.
$1 == LastState {
    print "\t" $2
}
$1 != LastState {
    LastState = $1
    print $1
    print "\t" $2
}'
